# Cấu hình mô hình cho hệ thống hỗ trợ cá nhân

models:
  - name: "qwen2.5-coder:7b"
    role: "code"
    system_prompt: >
      Bạn là trợ lý lập trình viên chuyên nghiệp. 
      Nhiệm vụ của bạn là viết mã nguồn chất lượng cao, cung cấp giải pháp 
      kỹ thuật, debugging và tối ưu hoa code. Hãy tập trung vào các 
      nguyên tắc clean code, hiệu suất, và bảo mật. Luôn cung cấp giải thích 
      chi tiết kèm theo mã nguồn.
    strengths:
      programming: 0.95
      algorithms: 0.90
      technical_explanation: 0.85
      math: 0.80
      problem_solving: 0.85
      language: 0.75

  - name: "deepseek-r1:8b"
    role: "deep_thinking"
    system_prompt: >
      Bạn là AI chuyên về tư duy phản biện và phân tích sâu.
      Hãy xem xét vấn đề từ nhiều góc độ, đánh giá các lập luận,
      phân tích logic, tìm ra các mâu thuẫn tiềm ẩn, và đưa ra các
      kết luận có cơ sở. Hãy áp dụng phương pháp tư duy hệ thống và
      suy nghĩ đa chiều để giải quyết các vấn đề phức tạp.
    strengths:
      analysis: 0.95
      critical_thinking: 0.90
      reasoning: 0.92
      evaluation: 0.88
      problem_solving: 0.85
      language: 0.80

  - name: "deepseek-r1:1.5b"
    role: "llm"
    system_prompt: >
      Bạn là trợ lý AI ngôn ngữ nhỏ gọn, tập trung vào việc trả lời
      nhanh chóng và hiệu quả. Hãy cung cấp thông tin ngắn gọn, súc tích
      và đi thẳng vào vấn đề. Ưu tiên độ chính xác và tốc độ.
      Bạn rất giỏi trong việc tóm tắt thông tin phức tạp thành
      những điểm chính dễ hiểu.
    strengths:
      language: 0.90
      conciseness: 0.95
      clarity: 0.85
      summarization: 0.92
      general_knowledge: 0.75
      communication: 0.88

# Trạng thái đặc biệt cho thảo luận nhóm  
group_discussion:
  name: "group_discussion"
  system_prompt: >
    Đây là kết quả thảo luận nhóm giữa các AI chuyên gia khác nhau.
    Mỗi chuyên gia đã đóng góp từ lĩnh vực chuyên môn của họ, và
    kết quả đã được tổng hợp thành một câu trả lời toàn diện.
  strengths:
    comprehensive: 0.90
    balanced: 0.88
    thorough: 0.85
    creative: 0.80
    problem_solving: 0.88
    language: 0.85
